name: Web lint check

on: [push, pull_request]

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint --quiet

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          restore-keys: node-npm-cache@
          key: node-npm-cache@${{ hashFiles('**/package-lock.json') }}
